name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
        env:
          TEXINPUTS: "./texmf/tex/latex/kulemt:"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis-pdf
          path: thesis.pdf
